### ISSUE TITLE
Position of undocked bar changes when window size changes and does not return to original location

### ISSUE THREAD

**Issue by tdewey7** [UnknownX7/QoLBar#13]
The position of an undocked bar in my setup slowly shifts over time as I switch between a maximized window and a non-maximized window. It is a single button in the bar on the lower left side of my screen the only thing non default in the style is the scale at 1.73. It is always visible and the behavior is the same whether it has its position locked or not. QoLBar version 1.3.1.1

Here is an example of the changes over time:

non-maximized(start): 12, 1064
maximized: 16, 1071
non-maximized: 11, 1063
maximized: 14, 1070
non-maximized: 10, 1062

... and so on. It appears to slowly creep back into the top left(0,0). Expected behavior would be for it to return to the original location when the screen returns to its previous size. Perhaps it is due to rounding with the adjustment it makes for the change in screen size? (just a guess based on observation)

Here is an export of the bar if it helps:

> H4sIAAAAAAAEAK1U207bQBD9Fcv0MU1jCIX6LQmlVECgOA0tTR8We+KsvN6J9oJqoXxUf6Tf1FnHJl4kpAr1wVrtmTNnPXNm9zF8Y6o1hHH4BS/GTPXpm6Bc8rwXbJGwF864EY5yiVaa4AxNARXByQqVSa254NqE8Y/H51JtvKM0ZaUjxHEUHe/tbfVu0AowBtxBdX7UCydYlkxmRH1X1qRFOBIGiMsNLMKFfILHPA+SFQjhoR9XQgQztB74SQEzwRy0BhHgksRkwTzGJct5WkAWjCHzU9m94pT157cHn4qKyzyYrBhXXuAEM/SAGxTCUWeMzlS++NclN9xDZpViUqJm1pc9R7XGorAqOEeBWlvth7ni0kOuyQFRBbT84n7fLiFnAo1iuROh3je2xtFBFL3/QO7a+62x0gpBYZ7BKCNHlkxo6NEsZGTVPlnFDOSoqluemRWlDwc7LDGs0ldrkE9pbWSCwpZS12Z/TlHeIZa06Q+226vlUgOdvZuppNIGyv7UlqB4qvtzSA2q/V7wLECVfAvjgRP6Xq+breKMy3/QG76gFzV69XrXrLf1utn8rLuTdaqcc83vueCmqls0EjyXJbgfoHJPMC0S7ro3dIkObdLG1hiUbSMHg07XjbJEuEZNo4Ly9Y05aAsZHB7WvblAN/A74eZX/q8BScrcAxL1jw46w9GCxLyBB2BiRBe0i56iNN19m/kcT9YspcsVxscd9RZ7bQXHTQXDuoIpjlla5Ipuz5MbU2wP28X0roM09k2cg76SZ/gAyovSDUtfJNAjnNWWJM6Gt9HmL5M43jeqBQAA

**Comment by UnknownX7** [comment]
It is because of rounding, but locked bars should always end up in their original positions if the game is reverted to the original size (and the bar wasn't unlocked at any point before reverting). I tried using your bar, but it seemed to always end up at the same position as I locked it at. In any case, I have a permanent solution for this issue planned, instead of my current bandaid (to stop shifting on unlocked bars as well), but it would require upgrading everyone's config, so its currently on hold until I finish compiling a list of more breaking changes to do all at once.

**Comment by UnknownX7** [comment]
This is fixed in the next update, bars will now position relative to screen size and no longer shift if they aren't moved (excluding cases where ImGui pushes them to keep them on screen if they are too far off). 1eac76ad317c58a778110b13659aa1e6ba555bc9
